document.write('<div style=" float: left;width: 978px;height: 132px;margin-left: -1px;background: url(images/footer.gif) bottom;">');
// class="foot_beta"
document.write('<div style=" width: 978px;margin-left: -1px;height: 29px;line-height: 29px;"></div>');
document.write('<table width="1075" border="0" cellspacing="0" cellpadding="3" align="center">');
document.write('<tr> ');
document.write('<td width="20%" align="right">');
document.write('<div align="right">');
document.write('<a href="http://61.144.125.15/netalarm/index.jsp" target="_blank" style="float: right;"><img style="float: right;" src="images/jj.gif" width="50" height="81" border="0" /></a> ');
document.write('</div>');
document.write('</td>');
document.write('<td width="30%">');
document.write('<table width="100%" border="0" cellspacing="0" cellpadding="3" class="css" align="center">');
document.write('<tr>');
document.write('<td width="129">');
document.write('<div align="right">');
document.write('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="125" height="40">');
document.write('<param name="movie" value="images/sdedulogo.swf" />');
document.write('<param name="quality" value="high" />');
document.write('<param name="menu" value="false" />');
document.write('<embed src="images/sdedulogo.swf" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="125" height="40" menu="false"> </embed>');
document.write('</object>');
document.write('</div>');
document.write('</td>');
document.write('<td width="285">顺德教育信息中心 版权所有 Copyright&copy; 2004<br />');
document.write('佛山市公安局网站公安备案编号:4406063011518<br />');
document.write('<a href="http://www.miibeian.gov.cn" target="_blank"> 粤ICP备05087326号</a>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');
document.write('</td>');
document.write('<td width="5%">');
document.write('<a href="http://210.76.65.188/webrecord/innernet/Welcome.jsp?bano=4406063011518" target="_blank"><img src="images/waicon.gif" width="35" height="47" border="0" /></a>');
document.write('</td>');
document.write('<td width="5%">');
document.write('<a href="http://210.76.65.188"><img src="images/baojing.gif" width="50" height="66" border="0" /></a>');
document.write('</td>');
document.write('<td width="20%">');
document.write('<a href="http://61.144.125.15/netalarm/index.jsp" target="_blank"><img src="images/cc.gif" width="50" height="81" border="0" /></a>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');